# permissions for end users to edit benchmarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: benchmark-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krkn-operator
    app.kubernetes.io/part-of: krkn-operator
    app.kubernetes.io/managed-by: kustomize
  name: benchmark-editor-role
rules:
- apiGroups:
  - perf.chaos.io
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.chaos.io
  resources:
  - benchmarks/status
  verbs:
  - get
